friend_demo: Cards.cpp CardsDriver.cpp GameEngine.cpp GameEngineDriver.cpp MainDriver.cpp Map.cpp MapDriver.cpp Orders.cpp OrdersDriver.cpp Player.cpp PlayerDriver.cpp
	g++ Cards.cpp CardsDriver.cpp GameEngine.cpp GameEngineDriver.cpp MainDriver.cpp Map.cpp MapDriver.cpp Orders.cpp OrdersDriver.cpp Player.cpp PlayerDriver.cpp -o friend_demo


run: friend_demo
	./friend_demo


clean:
	rm -f friend_demo
	